import { definitions } from './index';

/**
 * Override autogenerated view definition as properties are not null/undefined
 */
export type StreamHistoryWithTotalViewCount = Required<
  definitions['stream_history_timestamp_with_total_view_count']
>;
