# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

env:
  # https://www.pulumi.com/docs/iac/cli/environment-variables/
  PULUMI_STACK:
    sh: ./scripts/stack-name.sh

tasks:
  build:
    cmd: ./scripts/build.sh

  create:
    desc: Creates a stack in pulumi with ESC values
    cmds:
      - |
        if ! pulumi stack select -s $PULUMI_STACK 2>/dev/null; then                                                   
          pulumi stack init -s $PULUMI_STACK
        fi
      - pulumi config env add emotes-service/dev --yes
      - pulumi config env add emotes-service/twitch-credentials --yes

  preview:
    desc: Preview any stack changes
    deps:
      - build
    cmds:
      - pulumi preview

  deploy:
    desc: Deploys IaC
    deps:
      - build
    cmds:
      - pulumi up --yes

  destroy:ci:
    desc: Teardown a stack from Pulumi and AWS without prompt
    cmds:
      - pulumi destroy --yes
      - pulumi stack rm $PULUMI_STACK --yes

  destroy:local:
    desc: Teardown a stack from Pulumi and AWS
    interactive: true
    cmds:
      - pulumi destroy
      - pulumi stack rm $PULUMI_STACK

  lint:
    cmd: gofmt -w .

  test:unit:
    cmd: go test ./...

  test:integration:
    cmd: go test -tags integration -v -count=1 ./src/tests/integration/...

  test:ci:
    cmds:
      - task: create
      - task: deploy
      - pulumi esc run emotes-service/dev -- go test -tags integration -v -count=1 ./...
